{% set python_min = "3.10" %}
{% set name = "lumicks.pylake" %}
{% set file_name = "lumicks_pylake" %}
{% set version = "1.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ file_name }}-{{ version }}.tar.gz
  sha256: a9170f582c2d6117c51ee67855bb8084169eadd54c7418b32cc52ec7d88930ea

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - wheel
    - setuptools >=69.3
  run:
    - python >={{ python_min }},<4
    - numpy >=1.24
    - matplotlib-base >=3.8
    - h5py >=3.4,<4
    - pytest >=7.4
    - scipy >=1.9,<2
    - tifffile >=2022.7.28
    - tabulate >=0.8.8,<0.11
    - cachetools >=3.1
    - deprecated >=1.2.8
    - scikit-learn >=0.18.0
    - scikit-image >=0.17.2
    - tqdm >=4.27.0
    - notebook >=7
    - ipywidgets >=7.0.0
    - jupyter_client >=8
    - ipympl >=0.9.3  # Needed for mpl 3.8 compatibility
test:
  imports:
    - lumicks.pylake
    - lumicks.pylake.tests
  requires:
    - python {{ python_min }}
    - pytest
  commands:
    - python -c "import lumicks.pylake as lk; import sys; sys.exit(lk.pytest())"

about:
  home: https://github.com/lumicks/pylake
  license: Apache-2.0
  license_file: license.md
  summary: Data analysis tools for Lumicks Bluelake
  dev_url: https://github.com/lumicks/pylake

extra:
  recipe-maintainers:
    - dean0x7d
    - JoepVanlier
    - tobiasjj
